version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - mongodb

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/my_database

  mongodb:
    image: mongo
    ports:
      - "27017:27017"